### PR TITLE
Add hsl and hsla color format support

### PR DESCRIPTION
**Pull request by Smankusors**
Well this library is using HSV color model, but doesn't support HSL/HSLA input format... So, why not add this feature into this library?

### CODE REVIEW

**Comment by NC22** [comment]
@Smankusors Thanks. I merge and added few little changes to prevent compatibility issues with private methods. I'll update minified version bit later

**Comment by Smankusors** [comment]
@NC22  ehm wait, why you updated the version from 1.19 to 1.2? The number feels like downgraded...

**Comment by NC22** [comment]
@Smankusors eh... its my habbit, I count minor changes as third digit or if reach 9 go to next second dig - so versions goes 1.2, 1.21, 1.22, 1.3 etc. I can add zero at the end if this confuse

**Comment by Smankusors** [comment]
@NC22 well I suggest that you write 1.21 as 1.2.1. But hey, that's up to you. But I find this is weird versioning 😮

**Pull request merged**
